name: Deploy Next.js App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js App
        run: |
          npm run build
          echo "Build complete. Directory structure:"
          ls -la
          echo ".next contents:"
          ls -la .next || echo "\u274C .next directory missing!"

      - name: Create tarball of build artifacts
        run: |
          tar -czf next-build.tar.gz .next public package*.json
          echo "Tarball created:"
          ls -lh *.tar.gz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: next-build.tar.gz
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .

      - name: Extract and verify build files
        run: |
          echo "Downloaded files:"
          ls -la
          
          if [ ! -f "next-build.tar.gz" ]; then
            echo "\u274C Tarball missing!"
            exit 1
          fi
          
          echo "Extracting files..."
          tar -xzf next-build.tar.gz
          
          echo "Extracted files:"
          ls -la
          ls -la .next || echo "\u274C .next still missing after extraction!"
          
          if [ ! -d ".next" ]; then
            echo "\u274C Critical error: .next directory missing after extraction!"
            echo "Debugging info:"
            file next-build.tar.gz
            tar -tzf next-build.tar.gz || echo "Failed to list tarball contents"
            exit 1
          fi

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.SERVER_USER }}
          APP_DIR: ${{ secrets.APP_DIR || '/var/www/nextjs' }}
          PM2_APP_NAME: ${{ secrets.PM2_APP_NAME || 'next-app' }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          rsync -avz --no-perms --no-owner --no-group --delete \
            -e "ssh -i deploy_key -o StrictHostKeyChecking=no" \
            .next/ \
            public/ \
            package*.json \
            $USER@$SERVER_IP:$APP_DIR/

          ssh -i deploy_key -o StrictHostKeyChecking=no $USER@$SERVER_IP <<EOF
            set -e
            cd $APP_DIR
            npm ci --production
            pm2 delete $PM2_APP_NAME || true
            pm2 start npm --name "$PM2_APP_NAME" -- start
            pm2 save
            pm2 list
          EOF

          rm -f deploy_key