name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          rsync -avz -e "ssh -i deploy_key.pem -o StrictHostKeyChecking=no" .next/ $USER@$SERVER_IP:/var/www/nextjs
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no $USER@$SERVER_IP << 'EOF'
            cd /var/www/nextjs
            npm install --production
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
          EOF